name: ☁️ WordCloud

# everday at 00:00 UTC.
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Readme with WordCloud ☁️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - name: Setup python 🐍
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d #v5.1.0
        with:
          python-version: 3.12

      - name: Install wordcloud 📦
        run: |
          pip install wordcloud

      - name: Get org repo name 📚
        uses: austenstone/get-org-repos@97cd5be0027a2640c2c16f18b2a5a4e5be008fe2 #v3.1.0
        with:
          github-token: ${{ secrets.TOKEN }}
          org: "nosportugal"
        id: get-org-repos

      - name: Generate wordcloud ☁️
        run: |
          wordcloud_cli --text text.txt --imagefile output.png --mode RGB --mask mask.png --scale 2 --min_word_length 2 --contour_width 0.1 --contour_color steelblue --random_state $RANDOM --prefer_horizontal 0.5 --margin 1 --max_words 2000 <<< ${{ steps.get-org-repos.outputs.repos }}
